### PR TITLE
added footer

### PR DESCRIPTION
**Pull request by Patil-Mandar**
Added footer with social handlers and quick links to other pages.

### CODE REVIEW

**Comment by mrinalstark** [comment]
Thank @Patil-Mandar for the contribution

**Comment by Patil-Mandar** [comment]
Your welcome!

**Comment by Patil-Mandar** [comment]
@mrinalstark can you please add hacktoberfest label to this PR.

**Comment by Patil-Mandar** [comment]
@mrinalstark add 'hacktoberfest-accepted' label to this PR asap

**Pull request merged**
